### ISSUE TITLE
New Sabnzbd alert icon?

### ISSUE THREAD

**Issue by seanvree** [caronc/nzb-notify#39]
OS: Windows 10
Sabnzbd
Agent:  Mattermost

Sab Notification script:
mmosts://sabnzbd@mydomain.com/ifeaht4hpxxxxxxxijxdpwfia8ih?verify=False

Issue:

Out of no where the icon that started to display for Sabnzbd is different. And it's being loaded from an insecure source See screenshot below:

![image](https://user-images.githubusercontent.com/8906637/35912805-80c2a420-0bb2-11e8-861d-9219cf1914db.png)

![image](https://user-images.githubusercontent.com/8906637/35912725-41308688-0bb2-11e8-8a31-e1f1bbd7d12c.png)

**Comment by seanvree** [comment]
@caronc  Yeah, I figured you were messing with something. no biggie. 

Nope, everything works fine!

**Comment by seanvree** [comment]
@caronc  I'm getting these errors now:

```
 Notification script returned exit code 1 and output "Traceback (most recent call last):
  File "C:\Program Files\SABnzbd\scripts\Notify.py", line 350, in <module>
    from nzbget import SCRIPT_MODE
  File "C:\Program Files\SABnzbd\scripts\Notify\nzbget\__init__.py", line 23, in <module>
    from .ScriptBase import *
  File "C:\Program Files\SABnzbd\scripts\Notify\nzbget\ScriptBase.py", line 2504
    except TypeError
                   ^
```

**Comment by caronc** [comment]
Have another go at it. (fixed it [here](d89416482ca2d42e4b7c482e95124398d7d142f5))

**Comment by seanvree** [comment]
@caronc  yeah, that worked. Still have the old icon tho. 

![image](https://user-images.githubusercontent.com/8906637/36397463-bef67fc2-1577-11e8-9a36-eb9525d34151.png)

**Comment by seanvree** [comment]
@caronc  all good brother. First world problems.

**Comment by caronc** [comment]
The icon looks similar to what it already is, but since it's a standalone notification service, i just gave it an nzb-notify custom icon. They'll look as follows (a variety of sizes depending on the notification service used):
**Success Messages**
![apprise-success-256x256](https://user-images.githubusercontent.com/850374/37261088-1a204362-2570-11e8-81ee-e62e412d7d74.png)
**Failure Messages**
![apprise-failure-256x256](https://user-images.githubusercontent.com/850374/37261089-1c4bdade-2570-11e8-81c0-b9bc8d45e092.png)
**Info Messages**
![apprise-info-256x256](https://user-images.githubusercontent.com/850374/37261090-1e91a058-2570-11e8-886c-9754c9bfb5d2.png)
**Warning Messages**
![apprise-warning-256x256](https://user-images.githubusercontent.com/850374/37261091-204fb3da-2570-11e8-97dd-1454fcd6c7ec.png)

Sound okay?

**Comment by seanvree** [comment]
@caronc love it man! Great idea!

TBH, I'm mostly concerned that the images are served from a secure source.  Can they not be served from the local repo?

**Comment by caronc** [comment]
Some notification services that support images can only display them via URL. Others are file based and can read the local ones shipped.  If you're concerned about privacy, you can turn off the image display. Alternatively, to address your concern about an insecure source, perhaps I could get the images to look back at the GitHub Repository instead of nuxref.com one?

**Comment by seanvree** [comment]
Yeah there's no point in serving the images from a  remote source. Just put them in the repo.

**Comment by caronc** [comment]
If you wouldn't mind, giver another go.  If it works i'll update apprise (the core module) to also source images from GitHub too instead of my nuxref.com host (it's one less thing for me to manage).

Thanks for all your feedback

**Comment by seanvree** [comment]
Looks good @caronc  Thanks brotha!
