### ISSUE TITLE
Notify on Dupe

### ISSUE THREAD

**Issue by Baswazz** [caronc/nzb-notify#43]
Notify is working on Success and Failure i would like to see the option to notify on duplicate. I am using Telegram notifications.

**Comment by caronc** [comment]
This is a great idea! I created a [support ticket](https://forum.nzbget.net/viewtopic.php?f=3&t=3225) on the NZBGet Forums because that is uncharted waters for me.

When i get an answer, I'll see what i can do! :smile:

**Comment by hugbug** [comment]
Duplicate handling is complex and works on many stages.
What exactly do you mean with **notify on duplicate** and why do you think you need this?

**Comment by caronc** [comment]
I can't speak for @Baswazz, but If I were to guess: I think he wants to be notified when an NZB-File was added to his queue but never download because the scoring applied deemed the file as a duplicate.

**Comment by Baswazz** [comment]
@carnoc You described exactly what i mean.

**Comment by caronc** [comment]
@hugbug do you think this is something you'd be able to hook into NZBGet? Perhaps through a _PostScript_ or _FeedScript_?

For a _PostScript_, it might just be a health flag such as **FAILURE/DUPE** (or something like that)? I'm not sure the effort level involved vs the reward at the end of the day though. I also don't know the code base as well as you do, so i'm just polling for your feedback at this point.

What are your thoughts?

**Comment by hugbug** [comment]
It's possible that I don't understand the request correctly. That's why I've asked @Baswazz to explain what exactly he wants and why he thinks he needs this.

> to be notified when an NZB-File was added to his queue but never download

Do you mean an nzb in history with status DUPE? When should the notification be sent? When nzb lands in history with status DUPE it still can be downloaded later if the corresponding download (which can be in queue at this moment) fails.

Postprocessing scripts cannot be used here (because there is nothing to post-process) but a new queue event (for queue-script) is possible.

**Comment by Baswazz** [comment]
It does happen i already downloaded a file with the same title but a better quality option appears. Then it is marked as dupe in History. Because of this i don't get any notification and have to check the histories dupe section often.

If it is possible i think the notification should be send after it is marked as dupe this way it can be identified as dupe in the notification itself.

**Comment by hugbug** [comment]
@Baswazz 
It seems you use automation software like Sonarr. In that case you don't need duplicate check in nzbget. Just switch option DupeCheck off and everything will be downloaded. Sonarr (or whatever tool you use) will decide what to download.

**Comment by Baswazz** [comment]
@hugbug 
I only use a RSS Feed with a filter no Sonarr.

**Comment by caronc** [comment]
Just to break the stalemate here, @hugbug are you kind of leaning to the thought that it would be very difficult to hook into and make scoring/dupe results available to external hooks?

@baswazz: is there a reason you're using the dupe check? It sounds like in your environment (based in what hugbug pointed out), the option is kind of working against you.

**Comment by hugbug** [comment]
@caronc:
A new queue event shouldn't be difficult to implement. Still I think it's not necessary: if one needs a notification for DUPE then I think the system isn't setup properly 😉

@Baswazz:
You should use score system in your rss filters. Then the better quality releases will be downloaded automatically when they appear in RSS. The [documentation for RSS](https://nzbget.net/rss#duplicate-scores) explains how to do that. If you need help configuring scores I'll be glad to assist (preferably on nzbget forum).

If you guys still need notification for DUPE this can also be implemented. Please create an issue on nzbget issue tracker; otherwise I may forget about this request.

**Comment by Baswazz** [comment]
@caronc @hugbug I don't have any scores configured, i was not aware of this possibility. If this works then dupe notifications should be unnecessary.
If i have any problem configuring i will let you know on the nzbget forum.
Thanks guys for the responses and help!
