### ISSUE TITLE
Support for Signal

### ISSUE THREAD

**Issue by keppo070** [caronc/nzb-notify#54]
I'm using an Telegram Bot at the moment for notification do you have any plans to give support for signal in nzb-notify?

**Comment by caronc** [comment]
Thanks for the request,

I presume you're speaking about https://signal.org/ ([community](https://community.signalusers.org/)/[github](https://github.com/signalapp)) ?

There doesn't appear to be any easy way to work with it in Python yet due to all the encryption that wraps around it.  It would be a very large undertaking (_today_).

The only other problem would be the url (signal://),  you'd have to provide it a key that's got like 1600+ characters in it (minimum) as a private key just to negotiate a connection.

I'm open to suggestions and/or ideas, but having a quick glance at it now; it probably wouldn't fit very well as a NZBGet/SABnzbd notification script.

**Comment by keppo070** [comment]
I was speaking of signal.org.  I tried to find an API which could be beneficial, but I cannot find one. I understand this is a large undertaking. 

I will continue to use your terrific script with Telegram. Thank you for having a glance.
